from __future__ import annotations

# Generated by scripts/gen_mujoco_stubs.py

import enum
from typing import Any, Final, IO, TypeAlias

class FatalError(Exception): ...
class Renderer:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
class GLContext:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class mjtAlignFree(enum.IntEnum):
    mjALIGNFREE_FALSE = 0
    mjALIGNFREE_TRUE = 1
    mjALIGNFREE_AUTO = 2

class mjtBias(enum.IntEnum):
    mjBIAS_NONE = 0
    mjBIAS_AFFINE = 1
    mjBIAS_MUSCLE = 2
    mjBIAS_USER = 3

class mjtBuiltin(enum.IntEnum):
    mjBUILTIN_NONE = 0
    mjBUILTIN_GRADIENT = 1
    mjBUILTIN_CHECKER = 2
    mjBUILTIN_FLAT = 3

class mjtButton(enum.IntEnum):
    mjBUTTON_NONE = 0
    mjBUTTON_LEFT = 1
    mjBUTTON_RIGHT = 2
    mjBUTTON_MIDDLE = 3

class mjtCamLight(enum.IntEnum):
    mjCAMLIGHT_FIXED = 0
    mjCAMLIGHT_TRACK = 1
    mjCAMLIGHT_TRACKCOM = 2
    mjCAMLIGHT_TARGETBODY = 3
    mjCAMLIGHT_TARGETBODYCOM = 4

class mjtCamOutBit(enum.IntEnum):
    mjCAMOUT_RGB = 1
    mjCAMOUT_DEPTH = 2
    mjCAMOUT_DIST = 4
    mjCAMOUT_NORMAL = 8
    mjCAMOUT_SEG = 16
    mjNCAMOUT = 5

class mjtCamera(enum.IntEnum):
    mjCAMERA_FREE = 0
    mjCAMERA_TRACKING = 1
    mjCAMERA_FIXED = 2
    mjCAMERA_USER = 3

class mjtCatBit(enum.IntEnum):
    mjCAT_STATIC = 1
    mjCAT_DYNAMIC = 2
    mjCAT_DECOR = 4
    mjCAT_ALL = 7

class mjtColorSpace(enum.IntEnum):
    mjCOLORSPACE_AUTO = 0
    mjCOLORSPACE_LINEAR = 1
    mjCOLORSPACE_SRGB = 2

class mjtConDataField(enum.IntEnum):
    mjCONDATA_FOUND = 0
    mjCONDATA_FORCE = 1
    mjCONDATA_TORQUE = 2
    mjCONDATA_DIST = 3
    mjCONDATA_POS = 4
    mjCONDATA_NORMAL = 5
    mjCONDATA_TANGENT = 6
    mjNCONDATA = 7

class mjtCone(enum.IntEnum):
    mjCONE_PYRAMIDAL = 0
    mjCONE_ELLIPTIC = 1

class mjtConstraint(enum.IntEnum):
    mjCNSTR_EQUALITY = 0
    mjCNSTR_FRICTION_DOF = 1
    mjCNSTR_FRICTION_TENDON = 2
    mjCNSTR_LIMIT_JOINT = 3
    mjCNSTR_LIMIT_TENDON = 4
    mjCNSTR_CONTACT_FRICTIONLESS = 5
    mjCNSTR_CONTACT_PYRAMIDAL = 6
    mjCNSTR_CONTACT_ELLIPTIC = 7

class mjtConstraintState(enum.IntEnum):
    mjCNSTRSTATE_SATISFIED = 0
    mjCNSTRSTATE_QUADRATIC = 1
    mjCNSTRSTATE_LINEARNEG = 2
    mjCNSTRSTATE_LINEARPOS = 3
    mjCNSTRSTATE_CONE = 4

class mjtDataType(enum.IntEnum):
    mjDATATYPE_REAL = 0
    mjDATATYPE_POSITIVE = 1
    mjDATATYPE_AXIS = 2
    mjDATATYPE_QUATERNION = 3

class mjtDepthMap(enum.IntEnum):
    mjDEPTH_ZERONEAR = 0
    mjDEPTH_ZEROFAR = 1

class mjtDisableBit(enum.IntEnum):
    mjDSBL_CONSTRAINT = 1
    mjDSBL_EQUALITY = 2
    mjDSBL_FRICTIONLOSS = 4
    mjDSBL_LIMIT = 8
    mjDSBL_CONTACT = 16
    mjDSBL_SPRING = 32
    mjDSBL_DAMPER = 64
    mjDSBL_GRAVITY = 128
    mjDSBL_CLAMPCTRL = 256
    mjDSBL_WARMSTART = 512
    mjDSBL_FILTERPARENT = 1024
    mjDSBL_ACTUATION = 2048
    mjDSBL_REFSAFE = 4096
    mjDSBL_SENSOR = 8192
    mjDSBL_MIDPHASE = 16384
    mjDSBL_EULERDAMP = 32768
    mjDSBL_AUTORESET = 65536
    mjDSBL_NATIVECCD = 131072
    mjDSBL_ISLAND = 262144
    mjNDISABLE = 19

class mjtDyn(enum.IntEnum):
    mjDYN_NONE = 0
    mjDYN_INTEGRATOR = 1
    mjDYN_FILTER = 2
    mjDYN_FILTEREXACT = 3
    mjDYN_MUSCLE = 4
    mjDYN_USER = 5

class mjtEnableBit(enum.IntEnum):
    mjENBL_OVERRIDE = 1
    mjENBL_ENERGY = 2
    mjENBL_FWDINV = 4
    mjENBL_INVDISCRETE = 8
    mjENBL_MULTICCD = 16
    mjENBL_SLEEP = 32
    mjNENABLE = 6

class mjtEq(enum.IntEnum):
    mjEQ_CONNECT = 0
    mjEQ_WELD = 1
    mjEQ_JOINT = 2
    mjEQ_TENDON = 3
    mjEQ_FLEX = 4
    mjEQ_FLEXVERT = 5
    mjEQ_FLEXSTRAIN = 6
    mjEQ_DISTANCE = 7

class mjtEvent(enum.IntEnum):
    mjEVENT_NONE = 0
    mjEVENT_MOVE = 1
    mjEVENT_PRESS = 2
    mjEVENT_RELEASE = 3
    mjEVENT_SCROLL = 4
    mjEVENT_KEY = 5
    mjEVENT_RESIZE = 6
    mjEVENT_REDRAW = 7
    mjEVENT_FILESDROP = 8

class mjtFlexSelf(enum.IntEnum):
    mjFLEXSELF_NONE = 0
    mjFLEXSELF_NARROW = 1
    mjFLEXSELF_BVH = 2
    mjFLEXSELF_SAP = 3
    mjFLEXSELF_AUTO = 4

class mjtFont(enum.IntEnum):
    mjFONT_NORMAL = 0
    mjFONT_SHADOW = 1
    mjFONT_BIG = 2

class mjtFontScale(enum.IntEnum):
    mjFONTSCALE_50 = 50
    mjFONTSCALE_100 = 100
    mjFONTSCALE_150 = 150
    mjFONTSCALE_200 = 200
    mjFONTSCALE_250 = 250
    mjFONTSCALE_300 = 300

class mjtFrame(enum.IntEnum):
    mjFRAME_NONE = 0
    mjFRAME_BODY = 1
    mjFRAME_GEOM = 2
    mjFRAME_SITE = 3
    mjFRAME_CAMERA = 4
    mjFRAME_LIGHT = 5
    mjFRAME_CONTACT = 6
    mjFRAME_WORLD = 7
    mjNFRAME = 8

class mjtFramebuffer(enum.IntEnum):
    mjFB_WINDOW = 0
    mjFB_OFFSCREEN = 1

class mjtGain(enum.IntEnum):
    mjGAIN_FIXED = 0
    mjGAIN_AFFINE = 1
    mjGAIN_MUSCLE = 2
    mjGAIN_USER = 3

class mjtGeom(enum.IntEnum):
    mjGEOM_PLANE = 0
    mjGEOM_HFIELD = 1
    mjGEOM_SPHERE = 2
    mjGEOM_CAPSULE = 3
    mjGEOM_ELLIPSOID = 4
    mjGEOM_CYLINDER = 5
    mjGEOM_BOX = 6
    mjGEOM_MESH = 7
    mjGEOM_SDF = 8
    mjNGEOMTYPES = 9
    mjGEOM_ARROW = 100
    mjGEOM_ARROW1 = 101
    mjGEOM_ARROW2 = 102
    mjGEOM_LINE = 103
    mjGEOM_LINEBOX = 104
    mjGEOM_FLEX = 105
    mjGEOM_SKIN = 106
    mjGEOM_LABEL = 107
    mjGEOM_TRIANGLE = 108
    mjGEOM_NONE = 1001

class mjtGeomInertia(enum.IntEnum):
    mjINERTIA_VOLUME = 0
    mjINERTIA_SHELL = 1

class mjtGridPos(enum.IntEnum):
    mjGRID_TOPLEFT = 0
    mjGRID_TOPRIGHT = 1
    mjGRID_BOTTOMLEFT = 2
    mjGRID_BOTTOMRIGHT = 3
    mjGRID_TOP = 4
    mjGRID_BOTTOM = 5
    mjGRID_LEFT = 6
    mjGRID_RIGHT = 7

class mjtInertiaFromGeom(enum.IntEnum):
    mjINERTIAFROMGEOM_FALSE = 0
    mjINERTIAFROMGEOM_TRUE = 1
    mjINERTIAFROMGEOM_AUTO = 2

class mjtIntegrator(enum.IntEnum):
    mjINT_EULER = 0
    mjINT_RK4 = 1
    mjINT_IMPLICIT = 2
    mjINT_IMPLICITFAST = 3

class mjtItem(enum.IntEnum):
    mjITEM_END = -2
    mjITEM_SECTION = -1
    mjITEM_SEPARATOR = 0
    mjITEM_STATIC = 1
    mjITEM_BUTTON = 2
    mjITEM_CHECKINT = 3
    mjITEM_CHECKBYTE = 4
    mjITEM_RADIO = 5
    mjITEM_RADIOLINE = 6
    mjITEM_SELECT = 7
    mjITEM_SLIDERINT = 8
    mjITEM_SLIDERNUM = 9
    mjITEM_EDITINT = 10
    mjITEM_EDITNUM = 11
    mjITEM_EDITFLOAT = 12
    mjITEM_EDITTXT = 13
    mjNITEM = 14

class mjtJacobian(enum.IntEnum):
    mjJAC_DENSE = 0
    mjJAC_SPARSE = 1
    mjJAC_AUTO = 2

class mjtJoint(enum.IntEnum):
    mjJNT_FREE = 0
    mjJNT_BALL = 1
    mjJNT_SLIDE = 2
    mjJNT_HINGE = 3

class mjtLRMode(enum.IntEnum):
    mjLRMODE_NONE = 0
    mjLRMODE_MUSCLE = 1
    mjLRMODE_MUSCLEUSER = 2
    mjLRMODE_ALL = 3

class mjtLabel(enum.IntEnum):
    mjLABEL_NONE = 0
    mjLABEL_BODY = 1
    mjLABEL_JOINT = 2
    mjLABEL_GEOM = 3
    mjLABEL_SITE = 4
    mjLABEL_CAMERA = 5
    mjLABEL_LIGHT = 6
    mjLABEL_TENDON = 7
    mjLABEL_ACTUATOR = 8
    mjLABEL_CONSTRAINT = 9
    mjLABEL_FLEX = 10
    mjLABEL_SKIN = 11
    mjLABEL_SELECTION = 12
    mjLABEL_SELPNT = 13
    mjLABEL_CONTACTPOINT = 14
    mjLABEL_CONTACTFORCE = 15
    mjLABEL_ISLAND = 16
    mjNLABEL = 17

class mjtLightType(enum.IntEnum):
    mjLIGHT_SPOT = 0
    mjLIGHT_DIRECTIONAL = 1
    mjLIGHT_POINT = 2
    mjLIGHT_IMAGE = 3

class mjtLimited(enum.IntEnum):
    mjLIMITED_FALSE = 0
    mjLIMITED_TRUE = 1
    mjLIMITED_AUTO = 2

class mjtMark(enum.IntEnum):
    mjMARK_NONE = 0
    mjMARK_EDGE = 1
    mjMARK_CROSS = 2
    mjMARK_RANDOM = 3

class mjtMeshBuiltin(enum.IntEnum):
    mjMESH_BUILTIN_NONE = 0
    mjMESH_BUILTIN_SPHERE = 1
    mjMESH_BUILTIN_HEMISPHERE = 2
    mjMESH_BUILTIN_CONE = 3
    mjMESH_BUILTIN_SUPERSPHERE = 4
    mjMESH_BUILTIN_SUPERTORUS = 5
    mjMESH_BUILTIN_WEDGE = 6
    mjMESH_BUILTIN_PLATE = 7

class mjtMeshInertia(enum.IntEnum):
    mjMESH_INERTIA_CONVEX = 0
    mjMESH_INERTIA_EXACT = 1
    mjMESH_INERTIA_LEGACY = 2
    mjMESH_INERTIA_SHELL = 3

class mjtMouse(enum.IntEnum):
    mjMOUSE_NONE = 0
    mjMOUSE_ROTATE_V = 1
    mjMOUSE_ROTATE_H = 2
    mjMOUSE_MOVE_V = 3
    mjMOUSE_MOVE_H = 4
    mjMOUSE_ZOOM = 5
    mjMOUSE_MOVE_V_REL = 6
    mjMOUSE_MOVE_H_REL = 7

class mjtObj(enum.IntEnum):
    mjOBJ_UNKNOWN = 0
    mjOBJ_BODY = 1
    mjOBJ_XBODY = 2
    mjOBJ_JOINT = 3
    mjOBJ_DOF = 4
    mjOBJ_GEOM = 5
    mjOBJ_SITE = 6
    mjOBJ_CAMERA = 7
    mjOBJ_LIGHT = 8
    mjOBJ_FLEX = 9
    mjOBJ_MESH = 10
    mjOBJ_SKIN = 11
    mjOBJ_HFIELD = 12
    mjOBJ_TEXTURE = 13
    mjOBJ_MATERIAL = 14
    mjOBJ_PAIR = 15
    mjOBJ_EXCLUDE = 16
    mjOBJ_EQUALITY = 17
    mjOBJ_TENDON = 18
    mjOBJ_ACTUATOR = 19
    mjOBJ_SENSOR = 20
    mjOBJ_NUMERIC = 21
    mjOBJ_TEXT = 22
    mjOBJ_TUPLE = 23
    mjOBJ_KEY = 24
    mjOBJ_PLUGIN = 25
    mjNOBJECT = 26
    mjOBJ_FRAME = 100
    mjOBJ_DEFAULT = 101
    mjOBJ_MODEL = 102

class mjtOrientation(enum.IntEnum):
    mjORIENTATION_QUAT = 0
    mjORIENTATION_AXISANGLE = 1
    mjORIENTATION_XYAXES = 2
    mjORIENTATION_ZAXIS = 3
    mjORIENTATION_EULER = 4

class mjtPertBit(enum.IntEnum):
    mjPERT_TRANSLATE = 1
    mjPERT_ROTATE = 2

class mjtPluginCapabilityBit(enum.IntEnum):
    mjPLUGIN_ACTUATOR = 1
    mjPLUGIN_SENSOR = 2
    mjPLUGIN_PASSIVE = 4
    mjPLUGIN_SDF = 8

class mjtProjection(enum.IntEnum):
    mjPROJ_PERSPECTIVE = 0
    mjPROJ_ORTHOGRAPHIC = 1

class mjtRayDataField(enum.IntEnum):
    mjRAYDATA_DIST = 0
    mjRAYDATA_DIR = 1
    mjRAYDATA_ORIGIN = 2
    mjRAYDATA_POINT = 3
    mjRAYDATA_NORMAL = 4
    mjRAYDATA_DEPTH = 5
    mjNRAYDATA = 6

class mjtRndFlag(enum.IntEnum):
    mjRND_SHADOW = 0
    mjRND_WIREFRAME = 1
    mjRND_REFLECTION = 2
    mjRND_ADDITIVE = 3
    mjRND_SKYBOX = 4
    mjRND_FOG = 5
    mjRND_HAZE = 6
    mjRND_DEPTH = 7
    mjRND_SEGMENT = 8
    mjRND_IDCOLOR = 9
    mjRND_CULL_FACE = 10
    mjNRNDFLAG = 11

class mjtSDFType(enum.IntEnum):
    mjSDFTYPE_SINGLE = 0
    mjSDFTYPE_INTERSECTION = 1
    mjSDFTYPE_MIDSURFACE = 2
    mjSDFTYPE_COLLISION = 3

class mjtSameFrame(enum.IntEnum):
    mjSAMEFRAME_NONE = 0
    mjSAMEFRAME_BODY = 1
    mjSAMEFRAME_INERTIA = 2
    mjSAMEFRAME_BODYROT = 3
    mjSAMEFRAME_INERTIAROT = 4

class mjtSection(enum.IntEnum):
    mjSECT_CLOSED = 0
    mjSECT_OPEN = 1
    mjSECT_FIXED = 2

class mjtSensor(enum.IntEnum):
    mjSENS_TOUCH = 0
    mjSENS_ACCELEROMETER = 1
    mjSENS_VELOCIMETER = 2
    mjSENS_GYRO = 3
    mjSENS_FORCE = 4
    mjSENS_TORQUE = 5
    mjSENS_MAGNETOMETER = 6
    mjSENS_RANGEFINDER = 7
    mjSENS_CAMPROJECTION = 8
    mjSENS_JOINTPOS = 9
    mjSENS_JOINTVEL = 10
    mjSENS_TENDONPOS = 11
    mjSENS_TENDONVEL = 12
    mjSENS_ACTUATORPOS = 13
    mjSENS_ACTUATORVEL = 14
    mjSENS_ACTUATORFRC = 15
    mjSENS_JOINTACTFRC = 16
    mjSENS_TENDONACTFRC = 17
    mjSENS_BALLQUAT = 18
    mjSENS_BALLANGVEL = 19
    mjSENS_JOINTLIMITPOS = 20
    mjSENS_JOINTLIMITVEL = 21
    mjSENS_JOINTLIMITFRC = 22
    mjSENS_TENDONLIMITPOS = 23
    mjSENS_TENDONLIMITVEL = 24
    mjSENS_TENDONLIMITFRC = 25
    mjSENS_FRAMEPOS = 26
    mjSENS_FRAMEQUAT = 27
    mjSENS_FRAMEXAXIS = 28
    mjSENS_FRAMEYAXIS = 29
    mjSENS_FRAMEZAXIS = 30
    mjSENS_FRAMELINVEL = 31
    mjSENS_FRAMEANGVEL = 32
    mjSENS_FRAMELINACC = 33
    mjSENS_FRAMEANGACC = 34
    mjSENS_SUBTREECOM = 35
    mjSENS_SUBTREELINVEL = 36
    mjSENS_SUBTREEANGMOM = 37
    mjSENS_INSIDESITE = 38
    mjSENS_GEOMDIST = 39
    mjSENS_GEOMNORMAL = 40
    mjSENS_GEOMFROMTO = 41
    mjSENS_CONTACT = 42
    mjSENS_E_POTENTIAL = 43
    mjSENS_E_KINETIC = 44
    mjSENS_CLOCK = 45
    mjSENS_TACTILE = 46
    mjSENS_PLUGIN = 47
    mjSENS_USER = 48

class mjtSleepPolicy(enum.IntEnum):
    mjSLEEP_AUTO = 0
    mjSLEEP_AUTO_NEVER = 1
    mjSLEEP_AUTO_ALLOWED = 2
    mjSLEEP_NEVER = 3
    mjSLEEP_ALLOWED = 4
    mjSLEEP_INIT = 5

class mjtSleepState(enum.IntEnum):
    mjS_STATIC = -1
    mjS_ASLEEP = 0
    mjS_AWAKE = 1

class mjtSolver(enum.IntEnum):
    mjSOL_PGS = 0
    mjSOL_CG = 1
    mjSOL_NEWTON = 2

class mjtStage(enum.IntEnum):
    mjSTAGE_NONE = 0
    mjSTAGE_POS = 1
    mjSTAGE_VEL = 2
    mjSTAGE_ACC = 3

class mjtState(enum.IntEnum):
    mjSTATE_TIME = 1
    mjSTATE_QPOS = 2
    mjSTATE_QVEL = 4
    mjSTATE_ACT = 8
    mjSTATE_HISTORY = 16
    mjSTATE_WARMSTART = 32
    mjSTATE_CTRL = 64
    mjSTATE_QFRC_APPLIED = 128
    mjSTATE_XFRC_APPLIED = 256
    mjSTATE_EQ_ACTIVE = 512
    mjSTATE_MOCAP_POS = 1024
    mjSTATE_MOCAP_QUAT = 2048
    mjSTATE_USERDATA = 4096
    mjSTATE_PLUGIN = 8192
    mjNSTATE = 14
    mjSTATE_PHYSICS = 30
    mjSTATE_FULLPHYSICS = 8223
    mjSTATE_USER = 8128
    mjSTATE_INTEGRATION = 16383

class mjtStereo(enum.IntEnum):
    mjSTEREO_NONE = 0
    mjSTEREO_QUADBUFFERED = 1
    mjSTEREO_SIDEBYSIDE = 2

class mjtTaskStatus(enum.IntEnum):
    mjTASK_NEW = 0
    mjTASK_QUEUED = 1
    mjTASK_COMPLETED = 2

class mjtTexture(enum.IntEnum):
    mjTEXTURE_2D = 0
    mjTEXTURE_CUBE = 1
    mjTEXTURE_SKYBOX = 2

class mjtTextureRole(enum.IntEnum):
    mjTEXROLE_USER = 0
    mjTEXROLE_RGB = 1
    mjTEXROLE_OCCLUSION = 2
    mjTEXROLE_ROUGHNESS = 3
    mjTEXROLE_METALLIC = 4
    mjTEXROLE_NORMAL = 5
    mjTEXROLE_OPACITY = 6
    mjTEXROLE_EMISSIVE = 7
    mjTEXROLE_RGBA = 8
    mjTEXROLE_ORM = 9
    mjNTEXROLE = 10

class mjtTimer(enum.IntEnum):
    mjTIMER_STEP = 0
    mjTIMER_FORWARD = 1
    mjTIMER_INVERSE = 2
    mjTIMER_POSITION = 3
    mjTIMER_VELOCITY = 4
    mjTIMER_ACTUATION = 5
    mjTIMER_CONSTRAINT = 6
    mjTIMER_ADVANCE = 7
    mjTIMER_POS_KINEMATICS = 8
    mjTIMER_POS_INERTIA = 9
    mjTIMER_POS_COLLISION = 10
    mjTIMER_POS_MAKE = 11
    mjTIMER_POS_PROJECT = 12
    mjTIMER_COL_BROAD = 13
    mjTIMER_COL_NARROW = 14
    mjNTIMER = 15

class mjtTrn(enum.IntEnum):
    mjTRN_JOINT = 0
    mjTRN_JOINTINPARENT = 1
    mjTRN_SLIDERCRANK = 2
    mjTRN_TENDON = 3
    mjTRN_SITE = 4
    mjTRN_BODY = 5
    mjTRN_UNDEFINED = 1000

class mjtVisFlag(enum.IntEnum):
    mjVIS_CONVEXHULL = 0
    mjVIS_TEXTURE = 1
    mjVIS_JOINT = 2
    mjVIS_CAMERA = 3
    mjVIS_ACTUATOR = 4
    mjVIS_ACTIVATION = 5
    mjVIS_LIGHT = 6
    mjVIS_TENDON = 7
    mjVIS_RANGEFINDER = 8
    mjVIS_CONSTRAINT = 9
    mjVIS_INERTIA = 10
    mjVIS_SCLINERTIA = 11
    mjVIS_PERTFORCE = 12
    mjVIS_PERTOBJ = 13
    mjVIS_CONTACTPOINT = 14
    mjVIS_ISLAND = 15
    mjVIS_CONTACTFORCE = 16
    mjVIS_CONTACTSPLIT = 17
    mjVIS_TRANSPARENT = 18
    mjVIS_AUTOCONNECT = 19
    mjVIS_COM = 20
    mjVIS_SELECT = 21
    mjVIS_STATIC = 22
    mjVIS_SKIN = 23
    mjVIS_FLEXVERT = 24
    mjVIS_FLEXEDGE = 25
    mjVIS_FLEXFACE = 26
    mjVIS_FLEXSKIN = 27
    mjVIS_BODYBVH = 28
    mjVIS_MESHBVH = 29
    mjVIS_SDFITER = 30
    mjNVISFLAG = 31

class mjtWarning(enum.IntEnum):
    mjWARN_INERTIA = 0
    mjWARN_CONTACTFULL = 1
    mjWARN_CNSTRFULL = 2
    mjWARN_VGEOMFULL = 3
    mjWARN_BADQPOS = 4
    mjWARN_BADQVEL = 5
    mjWARN_BADQACC = 6
    mjWARN_BADCTRL = 7
    mjNWARNING = 8

class mjtWrap(enum.IntEnum):
    mjWRAP_NONE = 0
    mjWRAP_JOINT = 1
    mjWRAP_PULLEY = 2
    mjWRAP_SITE = 3
    mjWRAP_SPHERE = 4
    mjWRAP_CYLINDER = 5

class MjByteVec:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class MjCharVec:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class MjContact:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    dist: float
    pos: Any
    frame: Any
    includemargin: float
    friction: Any
    solref: Any
    solreffriction: Any
    solimp: Any
    mu: float
    H: Any
    dim: int
    geom1: int
    geom2: int
    geom: Any
    flex: Any
    elem: Any
    vert: Any
    exclude: int
    efc_address: int

class MjData:
    def __init__(self, model: MjModel) -> None: ...
    narena: int
    nbuffer: int
    nplugin: int
    pstack: int
    pbase: int
    parena: int
    maxuse_stack: int
    maxuse_threadstack: Any
    maxuse_arena: int
    maxuse_con: int
    maxuse_efc: int
    solver: Any
    solver_niter: Any
    solver_nnz: Any
    solver_fwdinv: Any
    warning: Any
    timer: Any
    ncon: int
    ne: int
    nf: int
    nl: int
    nefc: int
    nJ: int
    nA: int
    nisland: int
    nidof: int
    ntree_awake: int
    nbody_awake: int
    nparent_awake: int
    nv_awake: int
    flg_energypos: int
    flg_energyvel: int
    flg_subtreevel: int
    flg_rnepost: int
    time: float
    energy: Any
    buffer: Any
    arena: Any
    qpos: Any
    qvel: Any
    act: Any
    history: Any
    qacc_warmstart: Any
    plugin_state: Any
    ctrl: Any
    qfrc_applied: Any
    xfrc_applied: Any
    eq_active: Any
    mocap_pos: Any
    mocap_quat: Any
    qacc: Any
    act_dot: Any
    userdata: Any
    sensordata: Any
    tree_asleep: Any
    plugin: Any
    plugin_data: Any
    xpos: Any
    xquat: Any
    xmat: Any
    xipos: Any
    ximat: Any
    xanchor: Any
    xaxis: Any
    geom_xpos: Any
    geom_xmat: Any
    site_xpos: Any
    site_xmat: Any
    cam_xpos: Any
    cam_xmat: Any
    light_xpos: Any
    light_xdir: Any
    subtree_com: Any
    cdof: Any
    cinert: Any
    flexvert_xpos: Any
    flexelem_aabb: Any
    flexedge_J: Any
    flexedge_length: Any
    flexvert_J: Any
    flexvert_length: Any
    bvh_aabb_dyn: Any
    ten_wrapadr: Any
    ten_wrapnum: Any
    ten_J: Any
    ten_length: Any
    wrap_obj: Any
    wrap_xpos: Any
    actuator_length: Any
    moment_rownnz: Any
    moment_rowadr: Any
    moment_colind: Any
    actuator_moment: Any
    crb: Any
    qM: Any
    M: Any
    qLD: Any
    qLDiagInv: Any
    bvh_active: Any
    tree_awake: Any
    body_awake: Any
    body_awake_ind: Any
    parent_awake_ind: Any
    dof_awake_ind: Any
    flexedge_velocity: Any
    ten_velocity: Any
    actuator_velocity: Any
    cvel: Any
    cdof_dot: Any
    qfrc_bias: Any
    qfrc_spring: Any
    qfrc_damper: Any
    qfrc_gravcomp: Any
    qfrc_fluid: Any
    qfrc_passive: Any
    subtree_linvel: Any
    subtree_angmom: Any
    qH: Any
    qHDiagInv: Any
    qDeriv: Any
    qLU: Any
    actuator_force: Any
    qfrc_actuator: Any
    qfrc_smooth: Any
    qacc_smooth: Any
    qfrc_constraint: Any
    qfrc_inverse: Any
    cacc: Any
    cfrc_int: Any
    cfrc_ext: Any
    contact: MjContact
    efc_type: Any
    efc_id: Any
    efc_J_rownnz: Any
    efc_J_rowadr: Any
    efc_J_rowsuper: Any
    efc_J_colind: Any
    efc_J: Any
    efc_pos: Any
    efc_margin: Any
    efc_frictionloss: Any
    efc_diagApprox: Any
    efc_KBIP: Any
    efc_D: Any
    efc_R: Any
    tendon_efcadr: Any
    tree_island: Any
    island_ntree: Any
    island_itreeadr: Any
    map_itree2tree: Any
    dof_island: Any
    island_nv: Any
    island_idofadr: Any
    island_dofadr: Any
    map_dof2idof: Any
    map_idof2dof: Any
    ifrc_smooth: Any
    iacc_smooth: Any
    iM_rownnz: Any
    iM_rowadr: Any
    iM_colind: Any
    iM: Any
    iLD: Any
    iLDiagInv: Any
    iacc: Any
    efc_island: Any
    island_ne: Any
    island_nf: Any
    island_nefc: Any
    island_iefcadr: Any
    map_efc2iefc: Any
    map_iefc2efc: Any
    iefc_type: Any
    iefc_id: Any
    iefc_J_rownnz: Any
    iefc_J_rowadr: Any
    iefc_J_rowsuper: Any
    iefc_J_colind: Any
    iefc_J: Any
    iefc_frictionloss: Any
    iefc_D: Any
    iefc_R: Any
    efc_AR_rownnz: Any
    efc_AR_rowadr: Any
    efc_AR_colind: Any
    efc_AR: Any
    efc_vel: Any
    efc_aref: Any
    efc_b: Any
    iefc_aref: Any
    iefc_state: Any
    iefc_force: Any
    efc_state: Any
    efc_force: Any
    ifrc_constraint: Any
    threadpool: int
    signature: int
    def actuator(self, *args: Any, **kwargs: Any) -> Any: ...
    def bind(self, *args: Any, **kwargs: Any) -> Any: ...
    def bind_scalar(self, *args: Any, **kwargs: Any) -> Any: ...
    def body(self, *args: Any, **kwargs: Any) -> Any: ...
    def cam(self, *args: Any, **kwargs: Any) -> Any: ...
    def camera(self, *args: Any, **kwargs: Any) -> Any: ...
    def geom(self, *args: Any, **kwargs: Any) -> Any: ...
    def jnt(self, *args: Any, **kwargs: Any) -> Any: ...
    def joint(self, *args: Any, **kwargs: Any) -> Any: ...
    def light(self, *args: Any, **kwargs: Any) -> Any: ...
    model: Any
    def sensor(self, *args: Any, **kwargs: Any) -> Any: ...
    def site(self, *args: Any, **kwargs: Any) -> Any: ...
    def ten(self, *args: Any, **kwargs: Any) -> Any: ...
    def tendon(self, *args: Any, **kwargs: Any) -> Any: ...

class MjDoubleVec:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class MjFloatVec:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class MjIntVec:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class MjLROpt:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    mode: int
    useexisting: int
    uselimit: int
    accel: float
    maxforce: float
    timeconst: float
    timestep: float
    inttotal: float
    interval: float
    tolrange: float

class MjModel:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    nq: int
    nv: int
    nu: int
    na: int
    nbody: int
    nbvh: int
    nbvhstatic: int
    nbvhdynamic: int
    noct: int
    njnt: int
    ntree: int
    nM: int
    nB: int
    nC: int
    nD: int
    ngeom: int
    nsite: int
    ncam: int
    nlight: int
    nflex: int
    nflexnode: int
    nflexvert: int
    nflexedge: int
    nflexelem: int
    nflexelemdata: int
    nflexelemedge: int
    nflexshelldata: int
    nflexevpair: int
    nflextexcoord: int
    nJfe: int
    nJfv: int
    nmesh: int
    nmeshvert: int
    nmeshnormal: int
    nmeshtexcoord: int
    nmeshface: int
    nmeshgraph: int
    nmeshpoly: int
    nmeshpolyvert: int
    nmeshpolymap: int
    nskin: int
    nskinvert: int
    nskintexvert: int
    nskinface: int
    nskinbone: int
    nskinbonevert: int
    nhfield: int
    nhfielddata: int
    ntex: int
    ntexdata: int
    nmat: int
    npair: int
    nexclude: int
    neq: int
    ntendon: int
    nJten: int
    nwrap: int
    nsensor: int
    nnumeric: int
    nnumericdata: int
    ntext: int
    ntextdata: int
    ntuple: int
    ntupledata: int
    nkey: int
    nmocap: int
    nplugin: int
    npluginattr: int
    nuser_body: int
    nuser_jnt: int
    nuser_geom: int
    nuser_site: int
    nuser_cam: int
    nuser_tendon: int
    nuser_actuator: int
    nuser_sensor: int
    nnames: int
    npaths: int
    nnames_map: int
    nJmom: int
    ngravcomp: int
    nemax: int
    njmax: int
    nconmax: int
    nuserdata: int
    nsensordata: int
    npluginstate: int
    nhistory: int
    narena: int
    nbuffer: int
    opt: MjOption
    vis: MjVisual
    stat: MjStatistic
    buffer: Any
    qpos0: Any
    qpos_spring: Any
    body_parentid: Any
    body_rootid: Any
    body_weldid: Any
    body_mocapid: Any
    body_jntnum: Any
    body_jntadr: Any
    body_dofnum: Any
    body_dofadr: Any
    body_treeid: Any
    body_geomnum: Any
    body_geomadr: Any
    body_simple: Any
    body_sameframe: Any
    body_pos: Any
    body_quat: Any
    body_ipos: Any
    body_iquat: Any
    body_mass: Any
    body_subtreemass: Any
    body_inertia: Any
    body_invweight0: Any
    body_gravcomp: Any
    body_margin: Any
    body_user: Any
    body_plugin: Any
    body_contype: Any
    body_conaffinity: Any
    body_bvhadr: Any
    body_bvhnum: Any
    bvh_depth: Any
    bvh_child: Any
    bvh_nodeid: Any
    bvh_aabb: Any
    oct_depth: Any
    oct_child: Any
    oct_aabb: Any
    oct_coeff: Any
    jnt_type: Any
    jnt_qposadr: Any
    jnt_dofadr: Any
    jnt_bodyid: Any
    jnt_group: Any
    jnt_limited: Any
    jnt_actfrclimited: Any
    jnt_actgravcomp: Any
    jnt_solref: Any
    jnt_solimp: Any
    jnt_pos: Any
    jnt_axis: Any
    jnt_stiffness: Any
    jnt_range: Any
    jnt_actfrcrange: Any
    jnt_margin: Any
    jnt_user: Any
    dof_bodyid: Any
    dof_jntid: Any
    dof_parentid: Any
    dof_treeid: Any
    dof_Madr: Any
    dof_simplenum: Any
    dof_solref: Any
    dof_solimp: Any
    dof_frictionloss: Any
    dof_armature: Any
    dof_damping: Any
    dof_invweight0: Any
    dof_M0: Any
    dof_length: Any
    tree_bodyadr: Any
    tree_bodynum: Any
    tree_dofadr: Any
    tree_dofnum: Any
    tree_sleep_policy: Any
    geom_type: Any
    geom_contype: Any
    geom_conaffinity: Any
    geom_condim: Any
    geom_bodyid: Any
    geom_dataid: Any
    geom_matid: Any
    geom_group: Any
    geom_priority: Any
    geom_plugin: Any
    geom_sameframe: Any
    geom_solmix: Any
    geom_solref: Any
    geom_solimp: Any
    geom_size: Any
    geom_aabb: Any
    geom_rbound: Any
    geom_pos: Any
    geom_quat: Any
    geom_friction: Any
    geom_margin: Any
    geom_gap: Any
    geom_fluid: Any
    geom_user: Any
    geom_rgba: Any
    site_type: Any
    site_bodyid: Any
    site_matid: Any
    site_group: Any
    site_sameframe: Any
    site_size: Any
    site_pos: Any
    site_quat: Any
    site_user: Any
    site_rgba: Any
    cam_mode: Any
    cam_bodyid: Any
    cam_targetbodyid: Any
    cam_pos: Any
    cam_quat: Any
    cam_poscom0: Any
    cam_pos0: Any
    cam_mat0: Any
    cam_projection: Any
    cam_fovy: Any
    cam_ipd: Any
    cam_resolution: Any
    cam_output: Any
    cam_sensorsize: Any
    cam_intrinsic: Any
    cam_user: Any
    light_mode: Any
    light_bodyid: Any
    light_targetbodyid: Any
    light_type: Any
    light_texid: Any
    light_castshadow: Any
    light_bulbradius: Any
    light_intensity: Any
    light_range: Any
    light_active: Any
    light_pos: Any
    light_dir: Any
    light_poscom0: Any
    light_pos0: Any
    light_dir0: Any
    light_attenuation: Any
    light_cutoff: Any
    light_exponent: Any
    light_ambient: Any
    light_diffuse: Any
    light_specular: Any
    flex_contype: Any
    flex_conaffinity: Any
    flex_condim: Any
    flex_priority: Any
    flex_solmix: Any
    flex_solref: Any
    flex_solimp: Any
    flex_friction: Any
    flex_margin: Any
    flex_gap: Any
    flex_internal: Any
    flex_selfcollide: Any
    flex_activelayers: Any
    flex_passive: Any
    flex_dim: Any
    flex_matid: Any
    flex_group: Any
    flex_interp: Any
    flex_nodeadr: Any
    flex_nodenum: Any
    flex_vertadr: Any
    flex_vertnum: Any
    flex_edgeadr: Any
    flex_edgenum: Any
    flex_elemadr: Any
    flex_elemnum: Any
    flex_elemdataadr: Any
    flex_elemedgeadr: Any
    flex_shellnum: Any
    flex_shelldataadr: Any
    flex_evpairadr: Any
    flex_evpairnum: Any
    flex_texcoordadr: Any
    flex_nodebodyid: Any
    flex_vertbodyid: Any
    flex_vertedgeadr: Any
    flex_vertedgenum: Any
    flex_vertedge: Any
    flex_edge: Any
    flex_edgeflap: Any
    flex_elem: Any
    flex_elemtexcoord: Any
    flex_elemedge: Any
    flex_elemlayer: Any
    flex_shell: Any
    flex_evpair: Any
    flex_vert: Any
    flex_vert0: Any
    flex_vertmetric: Any
    flex_node: Any
    flex_node0: Any
    flexedge_length0: Any
    flexedge_invweight0: Any
    flex_radius: Any
    flex_size: Any
    flex_stiffness: Any
    flex_bending: Any
    flex_damping: Any
    flex_edgestiffness: Any
    flex_edgedamping: Any
    flex_edgeequality: Any
    flex_rigid: Any
    flexedge_rigid: Any
    flex_centered: Any
    flex_flatskin: Any
    flex_bvhadr: Any
    flex_bvhnum: Any
    flexedge_J_rownnz: Any
    flexedge_J_rowadr: Any
    flexedge_J_colind: Any
    flexvert_J_rownnz: Any
    flexvert_J_rowadr: Any
    flexvert_J_colind: Any
    flex_rgba: Any
    flex_texcoord: Any
    mesh_vertadr: Any
    mesh_vertnum: Any
    mesh_faceadr: Any
    mesh_facenum: Any
    mesh_bvhadr: Any
    mesh_bvhnum: Any
    mesh_octadr: Any
    mesh_octnum: Any
    mesh_normaladr: Any
    mesh_normalnum: Any
    mesh_texcoordadr: Any
    mesh_texcoordnum: Any
    mesh_graphadr: Any
    mesh_vert: Any
    mesh_normal: Any
    mesh_texcoord: Any
    mesh_face: Any
    mesh_facenormal: Any
    mesh_facetexcoord: Any
    mesh_graph: Any
    mesh_scale: Any
    mesh_pos: Any
    mesh_quat: Any
    mesh_pathadr: Any
    mesh_polynum: Any
    mesh_polyadr: Any
    mesh_polynormal: Any
    mesh_polyvertadr: Any
    mesh_polyvertnum: Any
    mesh_polyvert: Any
    mesh_polymapadr: Any
    mesh_polymapnum: Any
    mesh_polymap: Any
    skin_matid: Any
    skin_group: Any
    skin_rgba: Any
    skin_inflate: Any
    skin_vertadr: Any
    skin_vertnum: Any
    skin_texcoordadr: Any
    skin_faceadr: Any
    skin_facenum: Any
    skin_boneadr: Any
    skin_bonenum: Any
    skin_vert: Any
    skin_texcoord: Any
    skin_face: Any
    skin_bonevertadr: Any
    skin_bonevertnum: Any
    skin_bonebindpos: Any
    skin_bonebindquat: Any
    skin_bonebodyid: Any
    skin_bonevertid: Any
    skin_bonevertweight: Any
    skin_pathadr: Any
    hfield_size: Any
    hfield_nrow: Any
    hfield_ncol: Any
    hfield_adr: Any
    hfield_data: Any
    hfield_pathadr: Any
    tex_type: Any
    tex_colorspace: Any
    tex_height: Any
    tex_width: Any
    tex_nchannel: Any
    tex_adr: Any
    tex_data: Any
    tex_pathadr: Any
    mat_texid: Any
    mat_texuniform: Any
    mat_texrepeat: Any
    mat_emission: Any
    mat_specular: Any
    mat_shininess: Any
    mat_reflectance: Any
    mat_metallic: Any
    mat_roughness: Any
    mat_rgba: Any
    pair_dim: Any
    pair_geom1: Any
    pair_geom2: Any
    pair_signature: Any
    pair_solref: Any
    pair_solreffriction: Any
    pair_solimp: Any
    pair_margin: Any
    pair_gap: Any
    pair_friction: Any
    exclude_signature: Any
    eq_type: Any
    eq_obj1id: Any
    eq_obj2id: Any
    eq_objtype: Any
    eq_active0: Any
    eq_solref: Any
    eq_solimp: Any
    eq_data: Any
    tendon_adr: Any
    tendon_num: Any
    tendon_matid: Any
    tendon_group: Any
    tendon_treenum: Any
    tendon_treeid: Any
    ten_J_rownnz: Any
    ten_J_rowadr: Any
    ten_J_colind: Any
    tendon_limited: Any
    tendon_actfrclimited: Any
    tendon_width: Any
    tendon_solref_lim: Any
    tendon_solimp_lim: Any
    tendon_solref_fri: Any
    tendon_solimp_fri: Any
    tendon_range: Any
    tendon_actfrcrange: Any
    tendon_margin: Any
    tendon_stiffness: Any
    tendon_damping: Any
    tendon_armature: Any
    tendon_frictionloss: Any
    tendon_lengthspring: Any
    tendon_length0: Any
    tendon_invweight0: Any
    tendon_user: Any
    tendon_rgba: Any
    wrap_type: Any
    wrap_objid: Any
    wrap_prm: Any
    actuator_trntype: Any
    actuator_dyntype: Any
    actuator_gaintype: Any
    actuator_biastype: Any
    actuator_trnid: Any
    actuator_actadr: Any
    actuator_actnum: Any
    actuator_group: Any
    actuator_history: Any
    actuator_historyadr: Any
    actuator_delay: Any
    actuator_ctrllimited: Any
    actuator_forcelimited: Any
    actuator_actlimited: Any
    actuator_dynprm: Any
    actuator_gainprm: Any
    actuator_biasprm: Any
    actuator_actearly: Any
    actuator_ctrlrange: Any
    actuator_forcerange: Any
    actuator_actrange: Any
    actuator_gear: Any
    actuator_cranklength: Any
    actuator_acc0: Any
    actuator_length0: Any
    actuator_lengthrange: Any
    actuator_user: Any
    actuator_plugin: Any
    sensor_type: Any
    sensor_datatype: Any
    sensor_needstage: Any
    sensor_objtype: Any
    sensor_objid: Any
    sensor_reftype: Any
    sensor_refid: Any
    sensor_intprm: Any
    sensor_dim: Any
    sensor_adr: Any
    sensor_cutoff: Any
    sensor_noise: Any
    sensor_history: Any
    sensor_historyadr: Any
    sensor_delay: Any
    sensor_interval: Any
    sensor_user: Any
    sensor_plugin: Any
    plugin: Any
    plugin_stateadr: Any
    plugin_statenum: Any
    plugin_attr: str | bytes
    plugin_attradr: Any
    numeric_adr: Any
    numeric_size: Any
    numeric_data: Any
    text_adr: Any
    text_size: Any
    text_data: str | bytes
    tuple_adr: Any
    tuple_size: Any
    tuple_objtype: Any
    tuple_objid: Any
    tuple_objprm: Any
    key_time: Any
    key_qpos: Any
    key_qvel: Any
    key_act: Any
    key_mpos: Any
    key_mquat: Any
    key_ctrl: Any
    name_bodyadr: Any
    name_jntadr: Any
    name_geomadr: Any
    name_siteadr: Any
    name_camadr: Any
    name_lightadr: Any
    name_flexadr: Any
    name_meshadr: Any
    name_skinadr: Any
    name_hfieldadr: Any
    name_texadr: Any
    name_matadr: Any
    name_pairadr: Any
    name_excludeadr: Any
    name_eqadr: Any
    name_tendonadr: Any
    name_actuatoradr: Any
    name_sensoradr: Any
    name_numericadr: Any
    name_textadr: Any
    name_tupleadr: Any
    name_keyadr: Any
    name_pluginadr: Any
    names: str | bytes
    names_map: Any
    paths: str | bytes
    B_rownnz: Any
    B_rowadr: Any
    B_colind: Any
    M_rownnz: Any
    M_rowadr: Any
    M_colind: Any
    mapM2M: Any
    D_rownnz: Any
    D_rowadr: Any
    D_diag: Any
    D_colind: Any
    mapM2D: Any
    mapD2M: Any
    signature: int
    def actuator(self, *args: Any, **kwargs: Any) -> Any: ...
    def bind(self, *args: Any, **kwargs: Any) -> Any: ...
    def bind_scalar(self, *args: Any, **kwargs: Any) -> Any: ...
    def body(self, *args: Any, **kwargs: Any) -> Any: ...
    def cam(self, *args: Any, **kwargs: Any) -> Any: ...
    def camera(self, *args: Any, **kwargs: Any) -> Any: ...
    def eq(self, *args: Any, **kwargs: Any) -> Any: ...
    def equality(self, *args: Any, **kwargs: Any) -> Any: ...
    def exclude(self, *args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def from_binary_path(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def from_xml_path(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def from_xml_string(*args: Any, **kwargs: Any) -> Any: ...
    def geom(self, *args: Any, **kwargs: Any) -> Any: ...
    def hfield(self, *args: Any, **kwargs: Any) -> Any: ...
    def jnt(self, *args: Any, **kwargs: Any) -> Any: ...
    def joint(self, *args: Any, **kwargs: Any) -> Any: ...
    def key(self, *args: Any, **kwargs: Any) -> Any: ...
    def keyframe(self, *args: Any, **kwargs: Any) -> Any: ...
    def light(self, *args: Any, **kwargs: Any) -> Any: ...
    def mat(self, *args: Any, **kwargs: Any) -> Any: ...
    def material(self, *args: Any, **kwargs: Any) -> Any: ...
    def mesh(self, *args: Any, **kwargs: Any) -> Any: ...
    def numeric(self, *args: Any, **kwargs: Any) -> Any: ...
    def pair(self, *args: Any, **kwargs: Any) -> Any: ...
    def sensor(self, *args: Any, **kwargs: Any) -> Any: ...
    def site(self, *args: Any, **kwargs: Any) -> Any: ...
    def skin(self, *args: Any, **kwargs: Any) -> Any: ...
    def tendon(self, *args: Any, **kwargs: Any) -> Any: ...
    def tex(self, *args: Any, **kwargs: Any) -> Any: ...
    def texture(self, *args: Any, **kwargs: Any) -> Any: ...
    def tuple(self, *args: Any, **kwargs: Any) -> Any: ...

class MjOption:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    timestep: float
    impratio: float
    tolerance: float
    ls_tolerance: float
    noslip_tolerance: float
    ccd_tolerance: float
    sleep_tolerance: float
    gravity: Any
    wind: Any
    magnetic: Any
    density: float
    viscosity: float
    o_margin: float
    o_solref: Any
    o_solimp: Any
    o_friction: Any
    integrator: int
    cone: int
    jacobian: int
    solver: int
    iterations: int
    ls_iterations: int
    noslip_iterations: int
    ccd_iterations: int
    disableflags: int
    enableflags: int
    disableactuator: int
    sdf_initpoints: int
    sdf_iterations: int

class MjSolverStat:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    improvement: float
    gradient: float
    lineslope: float
    nactive: int
    nchange: int
    neval: int
    nupdate: int

class MjSpec:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    modelname: Any
    compiler: MjsCompiler
    strippath: int
    option: MjOption
    visual: MjVisual
    stat: MjStatistic
    memory: int
    nemax: int
    nuserdata: int
    nuser_body: int
    nuser_jnt: int
    nuser_geom: int
    nuser_site: int
    nuser_cam: int
    nuser_tendon: int
    nuser_actuator: int
    nuser_sensor: int
    nkey: int
    njmax: int
    nconmax: int
    nstack: int
    comment: Any
    modelfiledir: Any
    hasImplicitPluginElem: int
    @staticmethod
    def from_file(filename: str, include: Any = ..., assets: Any = ...) -> MjSpec: ...
    @staticmethod
    def from_string(xml: str, include: Any = ..., assets: Any = ...) -> MjSpec: ...
    @staticmethod
    def from_zip(file: str | IO[bytes]) -> MjSpec: ...
    def compile(self) -> MjModel: ...
    def to_xml(self) -> str: ...
    def body(self, name: str) -> MjsBody | None: ...
    def joint(self, name: str) -> MjsJoint | None: ...
    def actuator(self, name: str) -> MjsActuator | None: ...
    def geom(self, name: str) -> MjsGeom | None: ...
    def site(self, name: str) -> MjsSite | None: ...
    def frame(self, name: str) -> MjsFrame | None: ...
    def camera(self, name: str) -> MjsCamera | None: ...
    def light(self, name: str) -> MjsLight | None: ...
    def material(self, name: str) -> MjsMaterial | None: ...
    def mesh(self, name: str) -> MjsMesh | None: ...
    def delete(self, obj: Any) -> None: ...
    def activate_plugin(self, *args: Any, **kwargs: Any) -> Any: ...
    actuators: Any
    def add_actuator(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_default(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_equality(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_exclude(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_flex(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_hfield(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_key(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_material(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_mesh(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_numeric(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_pair(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_plugin(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_sensor(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_skin(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_tendon(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_text(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_texture(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_tuple(self, *args: Any, **kwargs: Any) -> Any: ...
    assets: Any
    def attach(self, *args: Any, **kwargs: Any) -> Any: ...
    bodies: Any
    cameras: Any
    def copy(self, *args: Any, **kwargs: Any) -> Any: ...
    copy_during_attach: Any
    default: Any
    equalities: Any
    def equality(self, *args: Any, **kwargs: Any) -> Any: ...
    def exclude(self, *args: Any, **kwargs: Any) -> Any: ...
    excludes: Any
    def find_default(self, *args: Any, **kwargs: Any) -> Any: ...
    def flex(self, *args: Any, **kwargs: Any) -> Any: ...
    flexes: Any
    frames: Any
    geoms: Any
    def hfield(self, *args: Any, **kwargs: Any) -> Any: ...
    hfields: Any
    joints: Any
    def key(self, *args: Any, **kwargs: Any) -> Any: ...
    keys: Any
    lights: Any
    materials: Any
    meshdir: Any
    meshes: Any
    def numeric(self, *args: Any, **kwargs: Any) -> Any: ...
    numerics: Any
    override_assets: Any
    def pair(self, *args: Any, **kwargs: Any) -> Any: ...
    pairs: Any
    parent: Any
    def plugin(self, *args: Any, **kwargs: Any) -> Any: ...
    plugins: Any
    def recompile(self, *args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def resolve_orientation(*args: Any, **kwargs: Any) -> Any: ...
    def sensor(self, *args: Any, **kwargs: Any) -> Any: ...
    sensors: Any
    sites: Any
    def skin(self, *args: Any, **kwargs: Any) -> Any: ...
    skins: Any
    def tendon(self, *args: Any, **kwargs: Any) -> Any: ...
    tendons: Any
    def text(self, *args: Any, **kwargs: Any) -> Any: ...
    texts: Any
    def texture(self, *args: Any, **kwargs: Any) -> Any: ...
    texturedir: Any
    textures: Any
    def to_file(self, *args: Any, **kwargs: Any) -> Any: ...
    def to_zip(self, *args: Any, **kwargs: Any) -> Any: ...
    def tuple(self, *args: Any, **kwargs: Any) -> Any: ...
    tuples: Any
    worldbody: Any

class MjStatistic:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    meaninertia: float
    meanmass: float
    meansize: float
    extent: float
    center: Any

class MjStringVec:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class MjTimerStat:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    duration: float
    number: int

class MjVisual:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    global_: Any
    quality: Any
    headlight: Any
    map: Any
    scale: Any
    rgba: Any
    def Global(self, *args: Any, **kwargs: Any) -> Any: ...
    def Headlight(self, *args: Any, **kwargs: Any) -> Any: ...
    def Map(self, *args: Any, **kwargs: Any) -> Any: ...
    def Quality(self, *args: Any, **kwargs: Any) -> Any: ...
    def Rgba(self, *args: Any, **kwargs: Any) -> Any: ...
    def Scale(self, *args: Any, **kwargs: Any) -> Any: ...

class MjVisualHeadlight:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    active: Any
    ambient: Any
    diffuse: Any
    specular: Any

class MjVisualRgba:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    actuator: Any
    actuatornegative: Any
    actuatorpositive: Any
    bv: Any
    bvactive: Any
    camera: Any
    com: Any
    connect: Any
    constraint: Any
    contactforce: Any
    contactfriction: Any
    contactgap: Any
    contactpoint: Any
    contacttorque: Any
    crankbroken: Any
    fog: Any
    force: Any
    frustum: Any
    haze: Any
    inertia: Any
    joint: Any
    light: Any
    rangefinder: Any
    selectpoint: Any
    slidercrank: Any

class MjWarningStat:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    lastinfo: int
    number: int

class MjrContext:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    lineWidth: float
    shadowClip: float
    shadowScale: float
    fogStart: float
    fogEnd: float
    fogRGBA: Any
    shadowSize: int
    offWidth: int
    offHeight: int
    offSamples: int
    fontScale: int
    auxWidth: Any
    auxHeight: Any
    auxSamples: Any
    offFBO: int
    offFBO_r: int
    offColor: int
    offColor_r: int
    offDepthStencil: int
    offDepthStencil_r: int
    shadowFBO: int
    shadowTex: int
    auxFBO: Any
    auxFBO_r: Any
    auxColor: Any
    auxColor_r: Any
    mat_texid: Any
    mat_texuniform: Any
    mat_texrepeat: Any
    ntexture: int
    textureType: Any
    texture: Any
    basePlane: int
    baseMesh: int
    baseHField: int
    baseBuiltin: int
    baseFontNormal: int
    baseFontShadow: int
    baseFontBig: int
    rangePlane: int
    rangeMesh: int
    rangeHField: int
    rangeBuiltin: int
    rangeFont: int
    nskin: int
    skinvertVBO: Any
    skinnormalVBO: Any
    skintexcoordVBO: Any
    skinfaceVBO: Any
    charWidth: Any
    charWidthBig: Any
    charHeight: int
    charHeightBig: int
    glInitialized: int
    windowAvailable: int
    windowSamples: int
    windowStereo: int
    windowDoublebuffer: int
    currentBuffer: int
    readPixelFormat: int
    readDepthMap: int
    def free(self, *args: Any, **kwargs: Any) -> Any: ...

class MjrRect:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    left: int
    bottom: int
    width: int
    height: int

class MjsActuator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    gaintype: mjtGain
    gainprm: Any
    biastype: mjtBias
    biasprm: Any
    dyntype: mjtDyn
    dynprm: Any
    actdim: int
    actearly: int
    trntype: mjtTrn
    gear: Any
    target: Any
    refsite: Any
    slidersite: Any
    cranklength: float
    lengthrange: Any
    inheritrange: float
    ctrllimited: int
    ctrlrange: Any
    forcelimited: int
    forcerange: Any
    actlimited: int
    actrange: Any
    group: int
    nsample: int
    interp: int
    delay: float
    userdata: Any
    plugin: MjsPlugin
    info: Any
    classname: Any
    compiler: Any
    id: Any
    name: Any
    def set_to_adhesion(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_to_cylinder(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_to_damper(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_to_intvelocity(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_to_motor(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_to_muscle(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_to_position(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_to_velocity(self, *args: Any, **kwargs: Any) -> Any: ...
    signature: Any

class MjsBody:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    childclass: Any
    pos: Any
    quat: Any
    alt: MjsOrientation
    mass: float
    ipos: Any
    iquat: Any
    inertia: Any
    ialt: MjsOrientation
    fullinertia: Any
    mocap: int
    gravcomp: float
    sleep: mjtSleepPolicy
    userdata: Any
    explicitinertial: int
    plugin: MjsPlugin
    info: Any
    def add_body(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_camera(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_frame(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_freejoint(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_geom(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_joint(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_light(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_site(self, *args: Any, **kwargs: Any) -> Any: ...
    def attach_frame(self, *args: Any, **kwargs: Any) -> Any: ...
    bodies: Any
    cameras: Any
    classname: Any
    compiler: Any
    def find_all(self, *args: Any, **kwargs: Any) -> Any: ...
    def find_child(self, *args: Any, **kwargs: Any) -> Any: ...
    def first_body(self, *args: Any, **kwargs: Any) -> Any: ...
    def first_camera(self, *args: Any, **kwargs: Any) -> Any: ...
    def first_frame(self, *args: Any, **kwargs: Any) -> Any: ...
    def first_geom(self, *args: Any, **kwargs: Any) -> Any: ...
    def first_joint(self, *args: Any, **kwargs: Any) -> Any: ...
    def first_light(self, *args: Any, **kwargs: Any) -> Any: ...
    def first_site(self, *args: Any, **kwargs: Any) -> Any: ...
    frame: Any
    frames: Any
    geoms: Any
    id: Any
    joints: Any
    lights: Any
    name: Any
    def next_body(self, *args: Any, **kwargs: Any) -> Any: ...
    def next_camera(self, *args: Any, **kwargs: Any) -> Any: ...
    def next_frame(self, *args: Any, **kwargs: Any) -> Any: ...
    def next_geom(self, *args: Any, **kwargs: Any) -> Any: ...
    def next_joint(self, *args: Any, **kwargs: Any) -> Any: ...
    def next_light(self, *args: Any, **kwargs: Any) -> Any: ...
    def next_site(self, *args: Any, **kwargs: Any) -> Any: ...
    parent: Any
    def set_frame(self, *args: Any, **kwargs: Any) -> Any: ...
    signature: Any
    sites: Any
    def to_frame(self, *args: Any, **kwargs: Any) -> Any: ...

class MjsCamera:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    pos: Any
    quat: Any
    alt: MjsOrientation
    mode: mjtCamLight
    targetbody: Any
    proj: mjtProjection
    resolution: Any
    output: int
    fovy: float
    ipd: float
    intrinsic: Any
    sensor_size: Any
    focal_length: Any
    focal_pixel: Any
    principal_length: Any
    principal_pixel: Any
    userdata: Any
    info: Any
    classname: Any
    compiler: Any
    frame: Any
    id: Any
    name: Any
    parent: Any
    def set_frame(self, *args: Any, **kwargs: Any) -> Any: ...
    signature: Any

class MjsCompiler:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    autolimits: int
    boundmass: float
    boundinertia: float
    settotalmass: float
    balanceinertia: int
    fitaabb: int
    degree: int
    eulerseq: Any
    discardvisual: int
    usethread: int
    fusestatic: int
    inertiafromgeom: int
    inertiagrouprange: Any
    saveinertial: int
    alignfree: int
    LRopt: MjLROpt
    meshdir: Any
    texturedir: Any

class MjsDefault:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    joint: MjsJoint
    geom: MjsGeom
    site: MjsSite
    camera: MjsCamera
    light: MjsLight
    flex: MjsFlex
    mesh: MjsMesh
    material: MjsMaterial
    pair: MjsPair
    equality: MjsEquality
    tendon: MjsTendon
    actuator: MjsActuator
    name: Any

class MjsElement:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    elemtype: mjtObj
    signature: int

class MjsEquality:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    type: mjtEq
    data: Any
    active: int
    name1: Any
    name2: Any
    objtype: mjtObj
    solref: Any
    solimp: Any
    info: Any
    classname: Any
    compiler: Any
    id: Any
    name: Any
    signature: Any

class MjsExclude:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    bodyname1: Any
    bodyname2: Any
    info: Any
    compiler: Any
    id: Any
    name: Any
    signature: Any

class MjsFlex:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    contype: int
    conaffinity: int
    condim: int
    priority: int
    friction: Any
    solmix: float
    solref: Any
    solimp: Any
    margin: float
    gap: float
    dim: int
    radius: float
    size: Any
    internal: int
    flatskin: int
    selfcollide: int
    vertcollide: int
    passive: int
    activelayers: int
    group: int
    edgestiffness: float
    edgedamping: float
    rgba: Any
    material: Any
    young: float
    poisson: float
    damping: float
    thickness: float
    elastic2d: int
    nodebody: Any
    vertbody: Any
    node: Any
    vert: Any
    elem: Any
    texcoord: Any
    elemtexcoord: Any
    info: Any
    compiler: Any
    id: Any
    name: Any
    signature: Any

class MjsFrame:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    childclass: Any
    pos: Any
    quat: Any
    alt: MjsOrientation
    info: Any
    def add_body(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_camera(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_frame(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_geom(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_joint(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_light(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_site(self, *args: Any, **kwargs: Any) -> Any: ...
    def attach_body(self, *args: Any, **kwargs: Any) -> Any: ...
    compiler: Any
    frame: Any
    id: Any
    name: Any
    parent: Any
    def set_frame(self, *args: Any, **kwargs: Any) -> Any: ...
    signature: Any

class MjsGeom:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    type: mjtGeom
    pos: Any
    quat: Any
    alt: MjsOrientation
    fromto: Any
    size: Any
    contype: int
    conaffinity: int
    condim: int
    priority: int
    friction: Any
    solmix: float
    solref: Any
    solimp: Any
    margin: float
    gap: float
    mass: float
    density: float
    typeinertia: mjtGeomInertia
    fluid_ellipsoid: float
    fluid_coefs: Any
    material: Any
    rgba: Any
    group: int
    hfieldname: Any
    meshname: Any
    fitscale: float
    userdata: Any
    plugin: MjsPlugin
    info: Any
    classname: Any
    compiler: Any
    frame: Any
    id: Any
    name: Any
    parent: Any
    def set_frame(self, *args: Any, **kwargs: Any) -> Any: ...
    signature: Any

class MjsHField:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    content_type: Any
    file: Any
    size: Any
    nrow: int
    ncol: int
    userdata: Any
    info: Any
    compiler: Any
    id: Any
    name: Any
    signature: Any

class MjsJoint:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    type: mjtJoint
    pos: Any
    axis: Any
    ref: float
    align: int
    stiffness: float
    springref: float
    springdamper: Any
    limited: int
    range: Any
    margin: float
    solref_limit: Any
    solimp_limit: Any
    actfrclimited: int
    actfrcrange: Any
    armature: float
    damping: float
    frictionloss: float
    solref_friction: Any
    solimp_friction: Any
    group: int
    actgravcomp: int
    userdata: Any
    info: Any
    classname: Any
    compiler: Any
    frame: Any
    id: Any
    name: Any
    parent: Any
    def set_frame(self, *args: Any, **kwargs: Any) -> Any: ...
    signature: Any

class MjsKey:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    time: float
    qpos: Any
    qvel: Any
    act: Any
    mpos: Any
    mquat: Any
    ctrl: Any
    info: Any
    compiler: Any
    id: Any
    name: Any
    signature: Any

class MjsLight:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    pos: Any
    dir: Any
    mode: mjtCamLight
    targetbody: Any
    active: int
    type: mjtLightType
    texture: Any
    castshadow: int
    bulbradius: float
    intensity: float
    range: float
    attenuation: Any
    cutoff: float
    exponent: float
    ambient: Any
    diffuse: Any
    specular: Any
    info: Any
    classname: Any
    compiler: Any
    frame: Any
    id: Any
    name: Any
    parent: Any
    def set_frame(self, *args: Any, **kwargs: Any) -> Any: ...
    signature: Any

class MjsMaterial:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    textures: Any
    texuniform: int
    texrepeat: Any
    emission: float
    specular: float
    shininess: float
    reflectance: float
    metallic: float
    roughness: float
    rgba: Any
    info: Any
    classname: Any
    compiler: Any
    id: Any
    name: Any
    signature: Any

class MjsMesh:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    content_type: Any
    file: Any
    refpos: Any
    refquat: Any
    scale: Any
    inertia: mjtMeshInertia
    smoothnormal: int
    needsdf: int
    maxhullvert: int
    uservert: Any
    usernormal: Any
    usertexcoord: Any
    userface: Any
    userfacenormal: Any
    userfacetexcoord: Any
    plugin: MjsPlugin
    material: Any
    info: Any
    classname: Any
    compiler: Any
    id: Any
    def make_cone(self, *args: Any, **kwargs: Any) -> Any: ...
    def make_hemisphere(self, *args: Any, **kwargs: Any) -> Any: ...
    def make_plate(self, *args: Any, **kwargs: Any) -> Any: ...
    def make_sphere(self, *args: Any, **kwargs: Any) -> Any: ...
    def make_supersphere(self, *args: Any, **kwargs: Any) -> Any: ...
    def make_supertorus(self, *args: Any, **kwargs: Any) -> Any: ...
    def make_wedge(self, *args: Any, **kwargs: Any) -> Any: ...
    name: Any
    signature: Any

class MjsNumeric:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    data: Any
    size: int
    info: Any
    compiler: Any
    id: Any
    name: Any
    signature: Any

class MjsOrientation:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    type: mjtOrientation
    axisangle: Any
    xyaxes: Any
    zaxis: Any
    euler: Any

class MjsPair:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    geomname1: Any
    geomname2: Any
    condim: int
    solref: Any
    solreffriction: Any
    solimp: Any
    margin: float
    gap: float
    friction: Any
    info: Any
    classname: Any
    compiler: Any
    id: Any
    name: Any
    signature: Any

class MjsPlugin:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    name: Any
    plugin_name: Any
    active: int
    info: Any
    compiler: Any
    config: Any
    id: Any
    signature: Any

class MjsSensor:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    type: mjtSensor
    objtype: mjtObj
    objname: Any
    reftype: mjtObj
    refname: Any
    intprm: Any
    datatype: mjtDataType
    needstage: mjtStage
    dim: int
    cutoff: float
    noise: float
    nsample: int
    interp: int
    delay: float
    interval: Any
    userdata: Any
    plugin: MjsPlugin
    info: Any
    compiler: Any
    def get_data_size(self, *args: Any, **kwargs: Any) -> Any: ...
    id: Any
    name: Any
    signature: Any

class MjsSite:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    pos: Any
    quat: Any
    alt: MjsOrientation
    fromto: Any
    size: Any
    type: mjtGeom
    material: Any
    group: int
    rgba: Any
    userdata: Any
    info: Any
    def attach_body(self, *args: Any, **kwargs: Any) -> Any: ...
    classname: Any
    compiler: Any
    frame: Any
    id: Any
    name: Any
    parent: Any
    def set_frame(self, *args: Any, **kwargs: Any) -> Any: ...
    signature: Any

class MjsSkin:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    file: Any
    material: Any
    rgba: Any
    inflate: float
    group: int
    vert: Any
    texcoord: Any
    face: Any
    bodyname: Any
    bindpos: Any
    bindquat: Any
    vertid: Any
    vertweight: Any
    info: Any
    compiler: Any
    id: Any
    name: Any
    signature: Any

class MjsTendon:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    stiffness: float
    springlength: Any
    damping: float
    frictionloss: float
    solref_friction: Any
    solimp_friction: Any
    armature: float
    limited: int
    actfrclimited: int
    range: Any
    actfrcrange: Any
    margin: float
    solref_limit: Any
    solimp_limit: Any
    material: Any
    width: float
    rgba: Any
    group: int
    userdata: Any
    info: Any
    compiler: Any
    def default(self, *args: Any, **kwargs: Any) -> Any: ...
    id: Any
    name: Any
    path: Any
    signature: Any
    def wrap_geom(self, *args: Any, **kwargs: Any) -> Any: ...
    def wrap_joint(self, *args: Any, **kwargs: Any) -> Any: ...
    def wrap_pulley(self, *args: Any, **kwargs: Any) -> Any: ...
    def wrap_site(self, *args: Any, **kwargs: Any) -> Any: ...

class MjsTendonPath:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class MjsText:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    data: Any
    info: Any
    compiler: Any
    id: Any
    name: Any
    signature: Any

class MjsTexture:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    type: mjtTexture
    colorspace: mjtColorSpace
    builtin: int
    mark: int
    rgb1: Any
    rgb2: Any
    markrgb: Any
    random: float
    height: int
    width: int
    nchannel: int
    content_type: Any
    file: Any
    gridsize: Any
    gridlayout: Any
    cubefiles: Any
    data: Any
    hflip: int
    vflip: int
    info: Any
    compiler: Any
    id: Any
    name: Any
    signature: Any

class MjsTuple:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    objtype: Any
    objname: Any
    objprm: Any
    info: Any
    compiler: Any
    id: Any
    name: Any
    signature: Any

class MjsWrap:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    element: MjsElement
    type: mjtWrap
    info: Any
    coef: Any
    divisor: Any
    sidesite: Any
    target: Any

class MjvCamera:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    type: int
    fixedcamid: int
    trackbodyid: int
    lookat: Any
    distance: float
    azimuth: float
    elevation: float
    orthographic: int

class MjvFigure:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    flg_legend: int
    flg_ticklabel: Any
    flg_extend: int
    flg_barplot: int
    flg_selection: int
    flg_symmetric: int
    linewidth: float
    gridwidth: float
    gridsize: Any
    gridrgb: Any
    figurergba: Any
    panergba: Any
    legendrgba: Any
    textrgb: Any
    linergb: Any
    range: Any
    xformat: Any
    yformat: Any
    minwidth: Any
    title: Any
    xlabel: Any
    linename: Any
    legendoffset: int
    subplot: int
    highlight: Any
    highlightid: int
    selection: float
    linepnt: Any
    linedata: Any
    xaxispixel: Any
    yaxispixel: Any
    xaxisdata: Any
    yaxisdata: Any

class MjvGLCamera:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    pos: Any
    forward: Any
    up: Any
    frustum_center: float
    frustum_width: float
    frustum_bottom: float
    frustum_top: float
    frustum_near: float
    frustum_far: float
    orthographic: int

class MjvGeom:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    type: int
    dataid: int
    objtype: int
    objid: int
    category: int
    matid: int
    texcoord: int
    segid: int
    size: Any
    pos: Any
    mat: Any
    rgba: Any
    emission: float
    specular: float
    shininess: float
    reflectance: float
    label: Any
    camdist: float
    modelrbound: float
    transparent: int

class MjvLight:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    id: int
    pos: Any
    dir: Any
    type: int
    texid: int
    attenuation: Any
    cutoff: float
    exponent: float
    ambient: Any
    diffuse: Any
    specular: Any
    headlight: int
    castshadow: int
    bulbradius: float
    intensity: float
    range: float

class MjvOption:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    label: int
    frame: int
    geomgroup: Any
    sitegroup: Any
    jointgroup: Any
    tendongroup: Any
    actuatorgroup: Any
    flexgroup: Any
    skingroup: Any
    flags: Any
    bvh_depth: int
    flex_layer: int

class MjvPerturb:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    select: int
    flexselect: int
    skinselect: int
    active: int
    active2: int
    refpos: Any
    refquat: Any
    refselpos: Any
    localpos: Any
    localmass: float
    scale: float

class MjvScene:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    maxgeom: int
    ngeom: int
    geoms: MjvGeom
    geomorder: Any
    nflex: int
    flexedgeadr: Any
    flexedgenum: Any
    flexvertadr: Any
    flexvertnum: Any
    flexfaceadr: Any
    flexfacenum: Any
    flexfaceused: Any
    flexedge: Any
    flexvert: Any
    flexface: Any
    flexnormal: Any
    flextexcoord: Any
    flexvertopt: int
    flexedgeopt: int
    flexfaceopt: int
    flexskinopt: int
    nskin: int
    skinfacenum: Any
    skinvertadr: Any
    skinvertnum: Any
    skinvert: Any
    skinnormal: Any
    nlight: int
    lights: Any
    camera: Any
    enabletransform: int
    translate: Any
    rotate: Any
    scale: float
    stereo: int
    flags: Any
    framewidth: int
    framergb: Any
    status: int

MjStruct: TypeAlias = Any

def to_zip(spec: MjSpec, file: str | IO[bytes]) -> None: ...
def from_zip(file: str | IO[bytes]) -> MjSpec: ...

def mj_Euler(m: MjModel, d: MjData) -> None: ...
def mj_RungeKutta(m: MjModel, d: MjData, N: int) -> None: ...
def mj_addContact(m: MjModel, d: MjData, con: MjContact) -> int: ...
def mj_addM(m: MjModel, d: MjData, dst: Any, rownnz: Any, rowadr: Any, colind: Any) -> None: ...
def mj_angmomMat(m: MjModel, d: MjData, mat: Any, body: int) -> None: ...
def mj_applyFT(m: MjModel, d: MjData, force: Any, torque: Any, point: Any, body: int, qfrc_target: Any) -> None: ...
def mj_camlight(m: MjModel, d: MjData) -> None: ...
def mj_checkAcc(m: MjModel, d: MjData) -> None: ...
def mj_checkPos(m: MjModel, d: MjData) -> None: ...
def mj_checkVel(m: MjModel, d: MjData) -> None: ...
def mj_clearCache(cache: Any) -> None: ...
def mj_collision(m: MjModel, d: MjData) -> None: ...
def mj_comPos(m: MjModel, d: MjData) -> None: ...
def mj_comVel(m: MjModel, d: MjData) -> None: ...
def mj_compareFwdInv(m: MjModel, d: MjData) -> None: ...
def mj_constraintUpdate(m: MjModel, d: MjData, jar: Any, cost: Any, flg_coneHessian: int) -> None: ...
def mj_contactForce(m: MjModel, d: MjData, id: int, result: Any) -> None: ...
def mj_copyData(dest: MjData, m: MjModel, src: MjData) -> MjData: ...
def mj_copyState(m: MjModel, src: MjData, dst: MjData, sig: int) -> None: ...
def mj_crb(m: MjModel, d: MjData) -> None: ...
def mj_defaultLROpt(opt: MjLROpt) -> None: ...
def mj_defaultOption(opt: MjOption) -> None: ...
def mj_defaultSolRefImp(solref: Any, solimp: Any) -> None: ...
def mj_defaultVisual(vis: MjVisual) -> None: ...
def mj_differentiatePos(m: MjModel, qvel: Any, dt: float, qpos1: Any, qpos2: Any) -> None: ...
def mj_energyPos(m: MjModel, d: MjData) -> None: ...
def mj_energyVel(m: MjModel, d: MjData) -> None: ...
def mj_extractState(m: MjModel, src: Any, srcsig: int, dst: Any, dstsig: int) -> None: ...
def mj_factorM(m: MjModel, d: MjData) -> None: ...
def mj_flex(m: MjModel, d: MjData) -> None: ...
def mj_forward(m: MjModel, d: MjData) -> None: ...
def mj_forwardSkip(m: MjModel, d: MjData, skipstage: int, skipsensor: int) -> None: ...
def mj_fullM(m: MjModel, dst: Any, M: Any) -> None: ...
def mj_fwdAcceleration(m: MjModel, d: MjData) -> None: ...
def mj_fwdActuation(m: MjModel, d: MjData) -> None: ...
def mj_fwdConstraint(m: MjModel, d: MjData) -> None: ...
def mj_fwdKinematics(m: MjModel, d: MjData) -> None: ...
def mj_fwdPosition(m: MjModel, d: MjData) -> None: ...
def mj_fwdVelocity(m: MjModel, d: MjData) -> None: ...
def mj_geomDistance(m: MjModel, d: MjData, geom1: int, geom2: int, distmax: float, fromto: Any) -> float: ...
def mj_getCache() -> Any: ...
def mj_getCacheCapacity(cache: Any) -> int: ...
def mj_getCacheSize(cache: Any) -> int: ...
def mj_getState(m: MjModel, d: MjData, state: Any, sig: int) -> None: ...
def mj_getTotalmass(m: MjModel) -> float: ...
def mj_id2name(m: MjModel, type: int, id: int) -> str | None: ...
def mj_implicit(m: MjModel, d: MjData) -> None: ...
def mj_initCtrlHistory(m: MjModel, d: MjData, id: int, times: Any, values: Any) -> None: ...
def mj_initSensorHistory(m: MjModel, d: MjData, id: int, times: Any, values: Any, phase: float) -> None: ...
def mj_integratePos(m: MjModel, qpos: Any, qvel: Any, dt: float) -> None: ...
def mj_invConstraint(m: MjModel, d: MjData) -> None: ...
def mj_invPosition(m: MjModel, d: MjData) -> None: ...
def mj_invVelocity(m: MjModel, d: MjData) -> None: ...
def mj_inverse(m: MjModel, d: MjData) -> None: ...
def mj_inverseSkip(m: MjModel, d: MjData, skipstage: int, skipsensor: int) -> None: ...
def mj_isDual(m: MjModel) -> int: ...
def mj_isPyramidal(m: MjModel) -> int: ...
def mj_isSparse(m: MjModel) -> int: ...
def mj_island(m: MjModel, d: MjData) -> None: ...
def mj_jac(m: MjModel, d: MjData, jacp: Any, jacr: Any, point: Any, body: int) -> None: ...
def mj_jacBody(m: MjModel, d: MjData, jacp: Any, jacr: Any, body: int) -> None: ...
def mj_jacBodyCom(m: MjModel, d: MjData, jacp: Any, jacr: Any, body: int) -> None: ...
def mj_jacDot(m: MjModel, d: MjData, jacp: Any, jacr: Any, point: Any, body: int) -> None: ...
def mj_jacGeom(m: MjModel, d: MjData, jacp: Any, jacr: Any, geom: int) -> None: ...
def mj_jacPointAxis(m: MjModel, d: MjData, jacPoint: Any, jacAxis: Any, point: Any, axis: Any, body: int) -> None: ...
def mj_jacSite(m: MjModel, d: MjData, jacp: Any, jacr: Any, site: int) -> None: ...
def mj_jacSubtreeCom(m: MjModel, d: MjData, jacp: Any, body: int) -> None: ...
def mj_kinematics(m: MjModel, d: MjData) -> None: ...
def mj_loadAllPluginLibraries(directory: str | bytes, callback: Any) -> None: ...
def mj_loadPluginLibrary(path: str | bytes) -> None: ...
def mj_local2Global(d: MjData, xpos: Any, xmat: Any, pos: Any, quat: Any, body: int, sameframe: int) -> None: ...
def mj_makeConstraint(m: MjModel, d: MjData) -> None: ...
def mj_makeM(m: MjModel, d: MjData) -> None: ...
def mj_mulJacTVec(m: MjModel, d: MjData, res: Any, vec: Any) -> None: ...
def mj_mulJacVec(m: MjModel, d: MjData, res: Any, vec: Any) -> None: ...
def mj_mulM(m: MjModel, d: MjData, res: Any, vec: Any) -> None: ...
def mj_mulM2(m: MjModel, d: MjData, res: Any, vec: Any) -> None: ...
def mj_multiRay(m: MjModel, d: MjData, pnt: Any, vec: Any, geomgroup: Any, flg_static: int, bodyexclude: int, geomid: Any, dist: Any, normal: Any, nray: int, cutoff: float) -> None: ...
def mj_name2id(m: MjModel, type: int, name: str | bytes) -> int: ...
def mj_normalizeQuat(m: MjModel, qpos: Any) -> None: ...
def mj_objectAcceleration(m: MjModel, d: MjData, objtype: int, objid: int, res: Any, flg_local: int) -> None: ...
def mj_objectVelocity(m: MjModel, d: MjData, objtype: int, objid: int, res: Any, flg_local: int) -> None: ...
def mj_passive(m: MjModel, d: MjData) -> None: ...
def mj_printData(m: MjModel, d: MjData, filename: str | bytes) -> None: ...
def mj_printFormattedData(m: MjModel, d: MjData, filename: str | bytes, float_format: str | bytes) -> None: ...
def mj_printFormattedModel(m: MjModel, filename: str | bytes, float_format: str | bytes) -> None: ...
def mj_printFormattedScene(s: MjvScene, filename: str | bytes, float_format: str | bytes) -> None: ...
def mj_printModel(m: MjModel, filename: str | bytes) -> None: ...
def mj_printScene(s: MjvScene, filename: str | bytes) -> None: ...
def mj_printSchema(filename: str | bytes, buffer: str | bytes, buffer_sz: int, flg_html: int, flg_pad: int) -> int: ...
def mj_projectConstraint(m: MjModel, d: MjData) -> None: ...
def mj_ray(m: MjModel, d: MjData, pnt: Any, vec: Any, geomgroup: Any, flg_static: int, bodyexclude: int, geomid: Any, normal: Any) -> float: ...
def mj_rayFlex(m: MjModel, d: MjData, flex_layer: int, flg_vert: int, flg_edge: int, flg_face: int, flg_skin: int, flexid: int, pnt: Any, vec: Any, vertid: Any, normal: Any) -> float: ...
def mj_rayHfield(m: MjModel, d: MjData, geomid: int, pnt: Any, vec: Any, normal: Any) -> float: ...
def mj_rayMesh(m: MjModel, d: MjData, geomid: int, pnt: Any, vec: Any, normal: Any) -> float: ...
def mj_readCtrl(m: MjModel, d: MjData, id: int, time: float, interp: int) -> float: ...
def mj_readSensor(m: MjModel, d: MjData, id: int, time: float, result: Any, interp: int) -> Any: ...
def mj_referenceConstraint(m: MjModel, d: MjData) -> None: ...
def mj_resetCallbacks() -> None: ...
def mj_resetData(m: MjModel, d: MjData) -> None: ...
def mj_resetDataDebug(m: MjModel, d: MjData, debug_value: int) -> None: ...
def mj_resetDataKeyframe(m: MjModel, d: MjData, key: int) -> None: ...
def mj_rne(m: MjModel, d: MjData, flg_acc: int, result: Any) -> None: ...
def mj_rnePostConstraint(m: MjModel, d: MjData) -> None: ...
def mj_saveLastXML(filename: str | bytes, m: MjModel, error: str | bytes, error_sz: int) -> int: ...
def mj_saveModel(m: MjModel, filename: str | bytes, buffer: Any, buffer_sz: int) -> None: ...
def mj_sensorAcc(m: MjModel, d: MjData) -> None: ...
def mj_sensorPos(m: MjModel, d: MjData) -> None: ...
def mj_sensorVel(m: MjModel, d: MjData) -> None: ...
def mj_setCacheCapacity(cache: Any, size: int) -> int: ...
def mj_setConst(m: MjModel, d: MjData) -> None: ...
def mj_setKeyframe(m: MjModel, d: MjData, k: int) -> None: ...
def mj_setLengthRange(m: MjModel, d: MjData, index: int, opt: MjLROpt, error: str | bytes, error_sz: int) -> int: ...
def mj_setState(m: MjModel, d: MjData, state: Any, sig: int) -> None: ...
def mj_setTotalmass(m: MjModel, newmass: float) -> None: ...
def mj_sizeModel(m: MjModel) -> int: ...
def mj_solveM(m: MjModel, d: MjData, x: Any, y: Any, n: int) -> None: ...
def mj_solveM2(m: MjModel, d: MjData, x: Any, y: Any, sqrtInvD: Any, n: int) -> None: ...
def mj_stateSize(m: MjModel, sig: int) -> int: ...
def mj_step(m: MjModel, d: MjData) -> None: ...
def mj_step1(m: MjModel, d: MjData) -> None: ...
def mj_step2(m: MjModel, d: MjData) -> None: ...
def mj_subtreeVel(m: MjModel, d: MjData) -> None: ...
def mj_tendon(m: MjModel, d: MjData) -> None: ...
def mj_transmission(m: MjModel, d: MjData) -> None: ...
def mj_version() -> int: ...
def mj_versionString() -> str | None: ...
def mjd_inverseFD(m: MjModel, d: MjData, eps: float, flg_actuation: int, DfDq: Any, DfDv: Any, DfDa: Any, DsDq: Any, DsDv: Any, DsDa: Any, DmDq: Any) -> None: ...
def mjd_quatIntegrate(vel: Any, scale: float, Dquat: Any, Dvel: Any, Dscale: Any) -> None: ...
def mjd_subQuat(qa: Any, qb: Any, Da: Any, Db: Any) -> None: ...
def mjd_transitionFD(m: MjModel, d: MjData, eps: float, flg_centered: int, A: Any, B: Any, C: Any, D: Any) -> None: ...
def mjr_addAux(index: int, width: int, height: int, samples: int, con: MjrContext) -> None: ...
def mjr_blitAux(index: int, src: MjrRect, left: int, bottom: int, con: MjrContext) -> None: ...
def mjr_blitBuffer(src: MjrRect, dst: MjrRect, flg_color: int, flg_depth: int, con: MjrContext) -> None: ...
def mjr_changeFont(fontscale: int, con: MjrContext) -> None: ...
def mjr_drawPixels(rgb: Any, depth: Any, viewport: MjrRect, con: MjrContext) -> None: ...
def mjr_figure(viewport: MjrRect, fig: MjvFigure, con: MjrContext) -> None: ...
def mjr_findRect(x: int, y: int, nrect: int, rect: MjrRect) -> int: ...
def mjr_finish() -> None: ...
def mjr_getError() -> int: ...
def mjr_label(viewport: MjrRect, font: int, txt: str | bytes, r: float, g: float, b: float, a: float, rt: float, gt: float, bt: float, con: MjrContext) -> None: ...
def mjr_maxViewport(con: MjrContext) -> MjrRect: ...
def mjr_overlay(font: int, gridpos: int, viewport: MjrRect, overlay: str | bytes, overlay2: str | bytes, con: MjrContext) -> None: ...
def mjr_readPixels(rgb: Any, depth: Any, viewport: MjrRect, con: MjrContext) -> None: ...
def mjr_rectangle(viewport: MjrRect, r: float, g: float, b: float, a: float) -> None: ...
def mjr_render(viewport: MjrRect, scn: MjvScene, con: MjrContext) -> None: ...
def mjr_resizeOffscreen(width: int, height: int, con: MjrContext) -> None: ...
def mjr_restoreBuffer(con: MjrContext) -> None: ...
def mjr_setAux(index: int, con: MjrContext) -> None: ...
def mjr_setBuffer(framebuffer: int, con: MjrContext) -> None: ...
def mjr_text(font: int, txt: str | bytes, con: MjrContext, x: float, y: float, r: float, g: float, b: float) -> None: ...
def mjr_uploadHField(m: MjModel, con: MjrContext, hfieldid: int) -> None: ...
def mjr_uploadMesh(m: MjModel, con: MjrContext, meshid: int) -> None: ...
def mjr_uploadTexture(m: MjModel, con: MjrContext, texid: int) -> None: ...
def mju_Halton(index: int, base: int) -> float: ...
def mju_L1(vec: Any, n: int) -> float: ...
def mju_add(res: Any, vec1: Any, vec2: Any, n: int) -> None: ...
def mju_add3(res: Any, vec1: Any, vec2: Any) -> None: ...
def mju_addScl(res: Any, vec1: Any, vec2: Any, scl: float, n: int) -> None: ...
def mju_addScl3(res: Any, vec1: Any, vec2: Any, scl: float) -> None: ...
def mju_addTo(res: Any, vec: Any, n: int) -> None: ...
def mju_addTo3(res: Any, vec: Any) -> None: ...
def mju_addToScl(res: Any, vec: Any, scl: float, n: int) -> None: ...
def mju_addToScl3(res: Any, vec: Any, scl: float) -> None: ...
def mju_axisAngle2Quat(res: Any, axis: Any, angle: float) -> None: ...
def mju_band2Dense(res: Any, mat: Any, ntotal: int, nband: int, ndense: int, flg_sym: int) -> None: ...
def mju_bandDiag(i: int, ntotal: int, nband: int, ndense: int) -> int: ...
def mju_bandMulMatVec(res: Any, mat: Any, vec: Any, ntotal: int, nband: int, ndense: int, nvec: int, flg_sym: int) -> None: ...
def mju_boxQP(res: Any, R: Any, index: Any, H: Any, g: Any, n: int, lower: Any, upper: Any) -> int: ...
def mju_cholFactor(mat: Any, n: int, mindiag: float) -> int: ...
def mju_cholFactorBand(mat: Any, ntotal: int, nband: int, ndense: int, diagadd: float, diagmul: float) -> float: ...
def mju_cholSolve(res: Any, mat: Any, vec: Any, n: int) -> None: ...
def mju_cholSolveBand(res: Any, mat: Any, vec: Any, ntotal: int, nband: int, ndense: int) -> None: ...
def mju_cholUpdate(mat: Any, x: Any, n: int, flg_plus: int) -> int: ...
def mju_clip(x: float, min: float, max: float) -> float: ...
def mju_copy(res: Any, vec: Any, n: int) -> None: ...
def mju_copy3(res: Any, data: Any) -> None: ...
def mju_copy4(res: Any, data: Any) -> None: ...
def mju_cross(res: Any, a: Any, b: Any) -> None: ...
def mju_d2n(res: Any, vec: Any, n: int) -> None: ...
def mju_decodePyramid(force: Any, pyramid: Any, mu: Any, dim: int) -> None: ...
def mju_dense2Band(res: Any, mat: Any, ntotal: int, nband: int, ndense: int) -> None: ...
def mju_dense2sparse(res: Any, mat: Any, nr: int, nc: int, rownnz: Any, rowadr: Any, colind: Any, nnz: int) -> int: ...
def mju_derivQuat(res: Any, quat: Any, vel: Any) -> None: ...
def mju_dist3(pos1: Any, pos2: Any) -> float: ...
def mju_dot(vec1: Any, vec2: Any, n: int) -> float: ...
def mju_dot3(vec1: Any, vec2: Any) -> float: ...
def mju_eig3(eigval: Any, eigvec: Any, quat: Any, mat: Any) -> int: ...
def mju_encodePyramid(pyramid: Any, force: Any, mu: Any, dim: int) -> None: ...
def mju_euler2Quat(quat: Any, euler: Any, seq: str | bytes) -> None: ...
def mju_eye(mat: Any, n: int) -> None: ...
def mju_f2n(res: Any, vec: Any, n: int) -> None: ...
def mju_fill(res: Any, val: float, n: int) -> None: ...
def mju_getXMLDependencies(filename: str | bytes, dependencies: Any) -> None: ...
def mju_insertionSort(list: Any, n: int) -> None: ...
def mju_insertionSortInt(list: Any, n: int) -> None: ...
def mju_isBad(x: float) -> int: ...
def mju_isZero(vec: Any, n: int) -> int: ...
def mju_mat2Quat(quat: Any, mat: Any) -> None: ...
def mju_mat2Rot(quat: Any, mat: Any) -> int: ...
def mju_max(a: float, b: float) -> float: ...
def mju_min(a: float, b: float) -> float: ...
def mju_mulMatMat(res: Any, mat1: Any, mat2: Any, r1: int, c1: int, c2: int) -> None: ...
def mju_mulMatMatT(res: Any, mat1: Any, mat2: Any, r1: int, c1: int, r2: int) -> None: ...
def mju_mulMatTMat(res: Any, mat1: Any, mat2: Any, r1: int, c1: int, c2: int) -> None: ...
def mju_mulMatTVec(res: Any, mat: Any, vec: Any, nr: int, nc: int) -> None: ...
def mju_mulMatTVec3(res: Any, mat: Any, vec: Any) -> None: ...
def mju_mulMatVec(res: Any, mat: Any, vec: Any, nr: int, nc: int) -> None: ...
def mju_mulMatVec3(res: Any, mat: Any, vec: Any) -> None: ...
def mju_mulPose(posres: Any, quatres: Any, pos1: Any, quat1: Any, pos2: Any, quat2: Any) -> None: ...
def mju_mulQuat(res: Any, quat1: Any, quat2: Any) -> None: ...
def mju_mulQuatAxis(res: Any, quat: Any, axis: Any) -> None: ...
def mju_mulVecMatVec(vec1: Any, mat: Any, vec2: Any, n: int) -> float: ...
def mju_muscleBias(len: float, lengthrange: Any, acc0: float, prm: Any) -> float: ...
def mju_muscleDynamics(ctrl: float, act: float, prm: Any) -> float: ...
def mju_muscleGain(len: float, vel: float, lengthrange: Any, acc0: float, prm: Any) -> float: ...
def mju_n2d(res: Any, vec: Any, n: int) -> None: ...
def mju_n2f(res: Any, vec: Any, n: int) -> None: ...
def mju_negPose(posres: Any, quatres: Any, pos: Any, quat: Any) -> None: ...
def mju_negQuat(res: Any, quat: Any) -> None: ...
def mju_norm(res: Any, n: int) -> float: ...
def mju_norm3(vec: Any) -> float: ...
def mju_normalize(res: Any, n: int) -> float: ...
def mju_normalize3(vec: Any) -> float: ...
def mju_normalize4(vec: Any) -> float: ...
def mju_printMat(mat: Any, nr: int, nc: int) -> None: ...
def mju_printMatSparse(mat: Any, nr: int, rownnz: Any, rowadr: Any, colind: Any) -> None: ...
def mju_quat2Mat(res: Any, quat: Any) -> None: ...
def mju_quat2Vel(res: Any, quat: Any, dt: float) -> None: ...
def mju_quatIntegrate(quat: Any, vel: Any, scale: float) -> None: ...
def mju_quatZ2Vec(quat: Any, vec: Any) -> None: ...
def mju_rayGeom(pos: Any, mat: Any, size: Any, pnt: Any, vec: Any, geomtype: int, normal: Any) -> float: ...
def mju_raySkin(nface: int, nvert: int, face: Any, vert: Any, pnt: Any, vec: Any, vertid: Any) -> float: ...
def mju_rotVecQuat(res: Any, vec: Any, quat: Any) -> None: ...
def mju_round(x: float) -> int: ...
def mju_scl(res: Any, vec: Any, scl: float, n: int) -> None: ...
def mju_scl3(res: Any, vec: Any, scl: float) -> None: ...
def mju_sigmoid(x: float) -> float: ...
def mju_sign(x: float) -> float: ...
def mju_sparse2dense(res: Any, mat: Any, nr: int, nc: int, rownnz: Any, rowadr: Any, colind: Any) -> None: ...
def mju_springDamper(pos0: float, vel0: float, Kp: float, Kv: float, dt: float) -> float: ...
def mju_sqrMatTD(res: Any, mat: Any, diag: Any, nr: int, nc: int) -> None: ...
def mju_standardNormal(num2: Any) -> float: ...
def mju_str2Type(str: str | bytes) -> int: ...
def mju_sub(res: Any, vec1: Any, vec2: Any, n: int) -> None: ...
def mju_sub3(res: Any, vec1: Any, vec2: Any) -> None: ...
def mju_subFrom(res: Any, vec: Any, n: int) -> None: ...
def mju_subFrom3(res: Any, vec: Any) -> None: ...
def mju_subQuat(res: Any, qa: Any, qb: Any) -> None: ...
def mju_sum(vec: Any, n: int) -> float: ...
def mju_symmetrize(res: Any, mat: Any, n: int) -> None: ...
def mju_transformSpatial(res: Any, vec: Any, flg_force: int, newpos: Any, oldpos: Any, rotnew2old: Any) -> None: ...
def mju_transpose(res: Any, mat: Any, nr: int, nc: int) -> None: ...
def mju_trnVecPose(res: Any, pos: Any, quat: Any, vec: Any) -> None: ...
def mju_type2Str(type: int) -> str | None: ...
def mju_unit4(res: Any) -> None: ...
def mju_warningText(warning: int, info: int) -> str | None: ...
def mju_writeLog(type: str | bytes, msg: str | bytes) -> None: ...
def mju_writeNumBytes(nbytes: int) -> str | None: ...
def mju_zero(res: Any, n: int) -> None: ...
def mju_zero3(res: Any) -> None: ...
def mju_zero4(res: Any) -> None: ...
def mjv_addGeoms(m: MjModel, d: MjData, opt: MjvOption, pert: MjvPerturb, catmask: int, scn: MjvScene) -> None: ...
def mjv_alignToCamera(res: Any, vec: Any, forward: Any) -> None: ...
def mjv_applyPerturbForce(m: MjModel, d: MjData, pert: MjvPerturb) -> None: ...
def mjv_applyPerturbPose(m: MjModel, d: MjData, pert: MjvPerturb, flg_paused: int) -> None: ...
def mjv_averageCamera(cam1: MjvGLCamera, cam2: MjvGLCamera) -> MjvGLCamera: ...
def mjv_cameraFrame(headpos: Any, forward: Any, up: Any, right: Any, d: MjData, cam: MjvCamera) -> None: ...
def mjv_cameraFrustum(zver: Any, zhor: Any, zclip: Any, m: MjModel, cam: MjvCamera) -> None: ...
def mjv_cameraInModel(headpos: Any, forward: Any, up: Any, scn: MjvScene) -> None: ...
def mjv_cameraInRoom(headpos: Any, forward: Any, up: Any, scn: MjvScene) -> None: ...
def mjv_connector(geom: MjvGeom, type: int, width: float, from_: Any, to: Any) -> None: ...
def mjv_defaultCamera(cam: MjvCamera) -> None: ...
def mjv_defaultFigure(fig: MjvFigure) -> None: ...
def mjv_defaultFreeCamera(m: MjModel, cam: MjvCamera) -> None: ...
def mjv_defaultOption(opt: MjvOption) -> None: ...
def mjv_defaultPerturb(pert: MjvPerturb) -> None: ...
def mjv_frustumHeight(scn: MjvScene) -> float: ...
def mjv_initGeom(geom: MjvGeom, type: int, size: Any, pos: Any, mat: Any, rgba: Any) -> None: ...
def mjv_initPerturb(m: MjModel, d: MjData, scn: MjvScene, pert: MjvPerturb) -> None: ...
def mjv_makeLights(m: MjModel, d: MjData, scn: MjvScene) -> None: ...
def mjv_model2room(roompos: Any, roomquat: Any, modelpos: Any, modelquat: Any, scn: MjvScene) -> None: ...
def mjv_moveCamera(m: MjModel, action: int, reldx: float, reldy: float, scn: MjvScene, cam: MjvCamera) -> None: ...
def mjv_moveModel(m: MjModel, action: int, reldx: float, reldy: float, roomup: Any, scn: MjvScene) -> None: ...
def mjv_movePerturb(m: MjModel, d: MjData, action: int, reldx: float, reldy: float, scn: MjvScene, pert: MjvPerturb) -> None: ...
def mjv_room2model(modelpos: Any, modelquat: Any, roompos: Any, roomquat: Any, scn: MjvScene) -> None: ...
def mjv_select(m: MjModel, d: MjData, vopt: MjvOption, aspectratio: float, relx: float, rely: float, scn: MjvScene, selpnt: Any, geomid: Any, flexid: Any, skinid: Any) -> int: ...
def mjv_updateCamera(m: MjModel, d: MjData, cam: MjvCamera, scn: MjvScene) -> None: ...
def mjv_updateScene(m: MjModel, d: MjData, opt: MjvOption, pert: MjvPerturb, cam: MjvCamera, catmask: int, scn: MjvScene) -> None: ...
def mjv_updateSkin(m: MjModel, d: MjData, scn: MjvScene) -> None: ...

HEADERS_DIR: Final[str]
PLUGINS_DIR: Final[str]
PLUGIN_HANDLES: Final[Any]
mjDISABLESTRING: Final[Any]
mjENABLESTRING: Final[Any]
mjFRAMESTRING: Final[Any]
mjLABELSTRING: Final[Any]
mjMAXCONPAIR: Final[int]
mjMAXFLEXNODES: Final[int]
mjMAXIMP: Final[float]
mjMAXLIGHT: Final[int]
mjMAXLINE: Final[int]
mjMAXLINEPNT: Final[int]
mjMAXOVERLAY: Final[int]
mjMAXPLANEGRID: Final[int]
mjMAXTREEDEPTH: Final[int]
mjMAXVAL: Final[float]
mjMINAWAKE: Final[int]
mjMINIMP: Final[float]
mjMINMU: Final[float]
mjMINVAL: Final[float]
mjNBIAS: Final[int]
mjNDYN: Final[int]
mjNEQDATA: Final[int]
mjNFLUID: Final[int]
mjNGAIN: Final[int]
mjNGROUP: Final[int]
mjNIMP: Final[int]
mjNISLAND: Final[int]
mjNREF: Final[int]
mjNSENS: Final[int]
mjNSOLVER: Final[int]
mjPI: Final[float]
mjRNDSTRING: Final[Any]
mjTIMERSTRING: Final[Any]
mjVERSION_HEADER: Final[int]
mjVISSTRING: Final[Any]

def __getattr__(name: str) -> Any: ...
